// src/components/Footer.tsx
/**
 * Copyright (c) 2018-present, Matei Bogdan Radu <matei.radu.92@gmail.com>
 *
 * This source code is licensed under the MIT license found in the LICENSE
 * file in the root directory of this source tree.
 */

import { h } from "preact";
import { Container } from ".";
import "./Footer.scss";

const projectRepo = "https://github.com/matt-block/personal-website";
const projectLincese = "https://github.com/matt-block/personal-website/blob/master/LICENSE";

export default () => (
  <footer>
    <Container>
      <p>Copyright © 2016-2018 Matei Bogdan Radu</p>
      <p>This website's source code is available on <a href={projectRepo}>GitHub</a> under the <a href={projectLincese}>MIT</a> license.</p>
    </Container>
  </footer>
);

// src/components/Footer.vue
<!--
  Copyright © 2016-2018 Matei Bogdan Radu <matei.radu.92@gmail.com>
  Licensed under MIT
  (https://github.com/mateiradu/personal-website/blob/master/LICENSE)
-->
<template>
  <footer role='contentinfo'>
    <div class='container'>
      <div class='divider'/>
      <p class='website-source'>Source code available on <a v-bind:href='source'>GitHub</a>.</p>
    </div>
  </footer>
</template>

<script>
export default {
  name: 'HelloWorld',
  data() {
    return {
      source: 'https://github.com/mateiradu/personal-website',
    };
  },
};
</script>

<style scoped>
footer {
  flex: none;
}

.website-source {
  margin-top: 21px;
  margin-bottom: 21px;
  font-size: 18px;
  line-height: 22px;
}

.divider {
  width: 100%;
  height: 1px;
  background-color: #707070;
}
</style>
